### ISSUE TITLE
F-measure is computed incorrectly for beta != 1

### ISSUE THREAD

**Issue by deGravity** [hhromic/python-bcubed#1]
The bcubed.fscore function is incorect

It is currently computed as
`(1.0 + beta) * (p_val * r_val / (beta**2 * p_val + r_val))`
while it should be
`(1.0 + beta**2) * (p_val * r_val / (beta**2 * p_val + r_val))`

**Comment by hhromic** [comment]
You are absolutely right. Shame on such dumb mistake :). I hope your results weren't affected that much and thanks a million for finding this bug (and providing the PR). I will merge, update and upload to pypi asap.
