### ISSUE TITLE
Different keys in cdict and ldict

### ISSUE THREAD

**Issue by peterdekker** [hhromic/python-bcubed#3]
From the documentation of python-bcubed, I understand that the keys in cdict and ldict are allowed to be different:

"Please note that the clusters names (or IDs) do not need to be the same as in the ground-truth data because the algorithm only considers the groupings, it does not try to match the names of clusters to the ground-truth categories."

However, when I call bcubed.recall, I get the following error (bcubed.precision gives a similar error):

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/bcubed/extended.py", line 30, in recall
>     for el2 in cdict if ldict[el1] & ldict[el2]]) for el1 in cdict])
> KeyError: '1'

The code in line 30 assumes that ldict and cdict have the same keys.

Could this possibly be fixed, or is this the desired behaviour of the library? In the last case, what would be a way for me to work around this? Thanks in advance!

**Comment by hhromic** [comment]
Hi @pdekker12 ,
I'm so sorry of replying so late to this. I didn't have time to review this at the moment I read your message and then I totally forgot about it.
Probably you don't have this issue anymore, however I would like to clarify it anyway for the sake of completetion and giving you a proper answer. Again my apologies.

The source code you mention does assume the same keys in `ldict` and `cdict`, and that is correct indeed. What I meant in my original comment is that the **cluster names or IDs** don't need to be the same. In `ldict` and `cdict` those are the sets of values in those dicts. From the `example.py` file included, you can take one example of each dict:

```python
# example ground-truth data (ldict)
ground_truth = {
    "item1": set(["gray", "black"]),
    "item2": set(["gray", "black"]),
    "item3": set(["gray"]),
    "item4": set(["black"]),
    "item5": set(["black"]),
    "item6": set(["dashed"]),
    "item7": set(["dashed"]),
}

# example clustering (cdict) in page 24, figure 16
clustering = {
    "item1": set(["A", "B"]),
    "item2": set(["A", "B"]),
    "item3": set(["A"]),
    "item4": set(["B"]),
    "item5": set(["B"]),
    "item6": set(["C"]),
    "item7": set(["C"]),
}
```

As you can see, the **keys** of `ldict` and `dict` (i.e. `item1`, `item`2, ...) are of the same domain and must be. However, the dict **values**, which are the clusters or groupings that those items belong to (i.e. `gray`, `black`, `A`, `B`, ...) do not need to be of the same domain (in this case colors and letters). Hope this clear and explain your finding.

Regarding working aorund this, I don't think you should as the purpose of evaluating clustering is comparing how well "items" are put into "groupings". And for ground-truth and your output, those items must be the same. Perhaps now that it's clearer after my explanation you can think again your problem?

Cheers and sorry again for the long delay replying.

**Comment by peterdekker** [comment]
Hi, thanks for your answer! My misunderstanding was indeed that I assumed the keys were clusters, while actually the values were the clusters. After I found this out, it worked perfectly! I use your library to evaluate cognate detection (clustering) algorithms in historical linguistics.

**Comment by hhromic** [comment]
I'm glad my implemention of the bcubed evaluation is being useful for your research.
Good luck and don't forget to cite the original authors of the work I implemented =).
Cheers
